services:
  simulator:
    build: .
    depends_on:
      - redis
    networks:
      - test
    deploy:
      replicas: 2

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - test

  prometheus-sim:
    image: prom/prometheus
    container_name: prometheus-sim
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ../prometheus/prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - test  

  grafana-sim:
    image: grafana/grafana
    container_name: grafana-sim
    restart: unless-stopped
    ports:
     - '3001:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - test  

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 9000:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    # for centos, fedora
    # - /cgroup:/cgroup:ro
    privileged: true
    depends_on:
    - redis    
    networks:
      - test

  # ngrok:
  #   image: ngrok/ngrok:latest
  #   restart: unless-stopped
  #   command:
  #     - "start"
  #     - "--all"
  #     - "--config"
  #     - "/etc/ngrok.yml"
  #   volumes:
  #     - ../ngrok/ngrok.yml:/etc/ngrok.yml
  #   ports:
  #     - 4040:4040    

volumes:
  grafana-storage: {}
  prom_data:

networks:
  test:
    name: test
