apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-server
  template:
    metadata:
      labels:
        app: rest-server
    spec:
      containers:
        - name: rest-server
          image: docker.io/ankush003/rest-server:latest
          ports:
            - containerPort: 8000
          env:
            - name: MONGODB_URI
              value: mongodb+srv://alertssim:RRdxdKTHt99cEnWw@cluster0.aenmhq0.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
            - name: KAFKA_BROKER
              value: active-boar-11578-us1-kafka.upstash.io:9092
            - name: KAFKA_USERNAME
              value: YWN0aXZlLWJvYXItMTE1NzgkSad0k7Y1TR2gDOgfvRl8R5Xs7vFQITViGMqTLl8
            - name: KAFKA_PASSWORD
              value: YTFmMTdhNDAtMWI3Mi00ZTcyLWE1MjItYzJlMjgzOTMxZjU3
            - name: REDIS_ADDR
              value: redis://default:ybaCdWLadAzqrb2qXO7QhKgjiDL3pXZ5@redis-16652.c212.ap-south-1-1.ec2.cloud.redislabs.com:16652