services:
  simulator:
    build: . 
    environment:
      - KAFKA_BROKER=192.168.49.1:9092
      - REDIS_ADDR=redis:6379
    scale: 2

  redis:
    image: redis:alpine
    ports:
      - "7000:6379"