name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push rule_engine
        uses: docker/build-push-action@v5
        with:
          context: ./middleware/rule_engine
          file: ./middleware/rule_engine/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/asmr-rule-engine:latest
      -
        name: Build and push rest_server
        uses: docker/build-push-action@v5
        with:
          context: ./middleware/rest_server
          file: ./middleware/rest_server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/asmr-rest-server:latest
      -
        name: Build and push simulator
        uses: docker/build-push-action@v5
        with:
          context: ./middleware/sim
          file: ./middleware/sim/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/asmr-simulator:latest
